### ISSUE TITLE
Compatibilty for Windows, and the use of the program as an "api endpoint"

### ISSUE THREAD

**Issue by Sup33r** [Ors1mer/QuadcastRGB#15]
Hello!

I was searching for a program that could change the color of the microphone by example a python script, on windows. And this repo seems pretty promising, even if it isn't for Windows.

**Comment by Ors1mer** [comment]
You are free to download the sources and try to compile them on windows. It might even work out of the box because libusb (the library `quadcastrgb` uses to talk to the mic) supports it. Otherwise, you'll have to make minor changes in the code.

I *will not* participate in porting/testing quadcastrgb on windows, but I could change the README if you find out that it runs successfully.

**Comment by Sup33r** [comment]
I managed to package a version for windows, and it kind of works, but regardless of the command used the microphone blinks in the same pattern. Is that something you have seen for the Mac or Linux versions? 

https://github.com/user-attachments/assets/496e5795-27f6-45d9-9255-155e50a9c97f

**Comment by Ors1mer** [comment]
No, I have not encountered such issues.

I'm sorry, but I don't know how to help you with this since I do not target windows as a supported OS.
